export const ENEMY_COLLECTION = {
    blighted_guardian: {
        en_name: 'Blighted Guardian',
        cn_name: '苦疫护卫',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    corpse_collector: {
        en_name: 'Corpse Collector',
        cn_name: '收尸花',
        def: 15,
        armor: 3,
        physic_resist: false,
        magic_resist: false,
    },
    enslaved_spirit: {
        en_name: 'Enslaved Spirit',
        cn_name: '拘役之灵',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    gatekeeper: {
        en_name: 'Gatekeeper',
        cn_name: '看门人',
        def: 12,
        armor: 2,
        physic_resist: false,
        magic_resist: false,
        ranged_resist: true,
    },
    gevaudan: {
        en_name: 'Gevaudan',
        cn_name: '狼',
        def: 16,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    lich_wurm: {
        en_name: 'Lich Wurm',
        cn_name: '巫妖',
        def: 13,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    living_oblation: {
        en_name: 'Living Oblation',
        cn_name: '活祭品',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    merk_hound: {
        en_name: 'Merk Hound',
        cn_name: '泽地猎犬',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    soul_butcher: {
        en_name: 'Soul Butcher',
        cn_name: '灵魂屠夫',
        def: 14,
        armor: 4,
        physic_resist: false,
        magic_resist: false,
    },
    tortured_immortal: {
        en_name: 'Tortured Immortal',
        cn_name: '不死者',
        def: 14,
        armor: 3,
        physic_resist: false,
        magic_resist: false,
    },
};
