export const ENEMY_COLLECTION = [
    {
        type: 'BLIGHTED_GUARDIAN',
        en_name: 'Blighted Guardian',
        cn_name: '枯萎疫护卫',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'CORPSE_COLLECTOR',
        en_name: 'Corpse Collector',
        cn_name: '收尸花',
        def: 15,
        armor: 3,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'ENSLAVED_SPIRIT',
        en_name: 'Enslaved Spirit',
        cn_name: '拘役之灵',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'GATEKEEPER',
        en_name: 'Gatekeeper',
        cn_name: '看门人',
        def: 12,
        armor: 2,
        physic_resist: false,
        magic_resist: false,
        ranged_resist: true,
    },
    {
        type: 'GEVAUDAN',
        en_name: 'Gevaudan',
        cn_name: '狼',
        def: 16,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'LICH_WURM',
        en_name: 'Lich Wurm',
        cn_name: '巫妖',
        def: 13,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'LIVING_OBLATION',
        en_name: 'Living Oblation',
        cn_name: '活祭品',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'MERK_HOUND',
        en_name: 'Merk Hound',
        cn_name: '泽地猎犬',
        def: 14,
        armor: 0,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'SOUL_BUTCHER',
        en_name: 'Soul Butcher',
        cn_name: '灵魂屠夫',
        def: 14,
        armor: 4,
        physic_resist: false,
        magic_resist: false,
    },
    {
        type: 'TORTURED_IMMORTAL',
        en_name: 'Tortured Immortal',
        cn_name: '不死者',
        def: 14,
        armor: 3,
        physic_resist: false,
        magic_resist: false,
    },
];
