export const ENEMY_COLLECTION = [
  {
    type: "BLIGHTED_GUARDIAN",
    name: "Blighted Guardian",
    cn_name: "枯萎疫护卫",
    def: 14,
    armor: 0,
    resistance: ["PHYSICAL", "MAGIC"],
    passive: [],
    activeResistance: ["PHYSICAL", "MAGIC"],
  },
  {
    type: "CORPSE_COLLECTOR",
    name: "Corpse Collector",
    cn_name: "收尸花",
    def: 15,
    armor: 3,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "ENSLAVED_SPIRIT",
    name: "Enslaved Spirit",
    cn_name: "拘役之灵",
    def: 14,
    armor: 0,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "GATEKEEPER",
    name: "Gatekeeper",
    cn_name: "看门人",
    def: 12,
    armor: 2,
    passive: [],
    resistance: ["RANGED"],
    activeResistance: ["RANGED"],
  },
  {
    type: "GEVAUDAN",
    name: "Gevaudan",
    cn_name: "狼",
    def: 16,
    armor: 0,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "LICH_WURM",
    name: "Lich Wurm",
    cn_name: "巫妖",
    def: 13,
    armor: 0,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "LIVING_OBLATION",
    name: "Living Oblation",
    cn_name: "活祭品",
    def: 14,
    armor: 0,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "MERK_HOUND",
    name: "Merk Hound",
    cn_name: "泽地猎犬",
    def: 14,
    armor: 0,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "SOUL_BUTCHER",
    name: "Soul Butcher",
    cn_name: "灵魂屠夫",
    def: 14,
    armor: 4,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
  {
    type: "TORTURED_IMMORTAL",
    name: "Tortured Immortal",
    cn_name: "不死者",
    def: 14,
    armor: 3,
    passive: [],
    resistance: [],
    activeResistance: [],
  },
];
