export const ALLY_NAMES = ['REMI', 'NIGHTINGALE', 'ROOK', 'ZEKE'];

export const ENEMY_NAMES = [
    'BLIGHTED_GUARDIAN',
    'CORPSE_COLLECTOR',
    'ENSLAVED_SPIRIT',
    'GATEKEEPER',
    'GEVAUDAN',
    'LICH_WURM',
    'LIVING_OBLATION',
    'MERK_HOUND',
    'SOUL_BUTCHER',
    'TORTURED_IMMORTAL',
];

export const DISCRIPLINE_NAMES = [
    'TRICK_SHOT',
    'CQC',
    'PRECISE_STRIKE',
    'DEAD_END',
    'HAMMER_HELM',
    'MASTER_OF_THE_VESSEL',
];

export const UPGRADE_NAMES = [
    'MASTER_WORK',
    'DEVASTATING',
    'OTHERWORLDLY',
    'IMBUED',
    'DARK',
];

export const DEBUFF_NAMES = ['DARKNESS', 'HINDERING', 'CROSS_ALLY', 'FLANKING'];
export const BUFF_NAMES = ['WILT', 'NEMESIS', 'COURAGE'];
